DRIVER_OBJECTS += bus/hsmci.o                \
	bus/console.o                 \
	bus/xdmad.o                   \
	bus/xdma_hardware_interface.o \
	bus/twi.o                     \
	bus/xdmac.o                   \
	bus/twid.o                    \
	bus/ssc.o                     \
	bus/spi.o                     \
	bus/can.o
