DRIVER_OBJECTS += io/ov7740_config.o \
	io/iso7816_4.o       \
	io/mt.o              \
	io/ov.o              \
	io/tsd_com.o         \
	io/tsd_tsadc.o       \
	io/ov2643_config.o   \
	io/ov9740_config.o   \
	io/ov5640_config.o   \
	io/mcid_dma.o        \
	io/qt1070.o          \
	io/ov2640_config.o   \
	io/mt9v022_config.o  \
	io/mtyuv.o           \
	io/aptina.o          \
	io/led.o             \
	io/omnivision.o
