DRIVER_OBJECTS += core/cortexa5_interrupts.o \
	core/l2cc.o     \
	core/adc.o      \
	core/pwmc.o     \
	core/cp15.o     \
	core/wdt.o      \
	core/aic.o      \
	core/rstc.o     \
	core/cp15_pmu.o \
	core/pmc.o      \
	core/async.o    \
	core/cpsr.o	\
	core/mmu.o      

DRIVER_OBJECTS_ASM += core/cp15_asm_gcc.o \
		   core/cpsr_gcc.o

ifeq (API_PIOv4,$(PIO_API))
DRIVER_OBJECTS += core/pio4.o
else
DRIVER_OBJECTS += core/pio3.o
endif
